# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Justin Burdett's Website
paginate:       5
baseurl:        ""
url:            "https://www.justinburdett.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Justin Burdett  
  url:          http://justinburdett.com
  email:        justin.burdett@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/jburdeezy/tale

# Gems
plugins:
  - jekyll-paginate
